// packages/react/src/ol-grid.tsx
import {
  createGridEngine,
  ModuleRegistry,
  type GridApi,
  type GridEngine,
  type GridOptions,
} from "@ol-grid/core";
import { SortModule } from "@ol-grid/sort";
import { FilterModule } from "@ol-grid/filter";
import { PaginationModule } from "@ol-grid/pagination";
import { createDomRenderer } from "@ol-grid/dom-renderer";
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useSyncExternalStore,
  type CSSProperties,
} from "react";
import { useCellRendererPortals } from "./cell-renderer-portals.js";

let sortModuleRegistered = false;
let filterModuleRegistered = false;
let paginationModuleRegistered = false;

function ensureSortModuleRegistered(): void {
  if (sortModuleRegistered) return;
  ModuleRegistry.register(SortModule);
  sortModuleRegistered = true;
}

function ensureFilterModuleRegistered(): void {
  if (filterModuleRegistered) return;
  ModuleRegistry.register(FilterModule);
  filterModuleRegistered = true;
}

function ensurePaginationModuleRegistered(): void {
  if (paginationModuleRegistered) return;
  ModuleRegistry.register(PaginationModule);
  paginationModuleRegistered = true;
}

export interface OlGridHandle<TData = unknown> {
  api: GridApi<TData>;
  grid: GridEngine<TData>;
}

export interface UseOlGridResult<TData> {
  grid: GridEngine<TData>;
  api: GridApi<TData>;
}

export interface OlGridProps<TData> extends GridOptions<TData> {
  className?: string;
  style?: CSSProperties;
}

const GRID_OPTION_KEYS = [
  "columnDefs",
  "rowData",
  "rowHeight",
  "rowSelection",
  "getRowId",
  "context",
  "quickFilterText",
  "sortModel",
  "filterModel",
  "pagination",
  "paginationPageSize",
  "paginationPage",
  "selectedRowIds",
  "defaultColDef",
  "theme",
  "locale",
  "localeText",
  "localeBundle",
] as const satisfies readonly (keyof GridOptions<unknown>)[];

type SyncedGridOptions<TData> = Partial<Pick<GridOptions<TData>, (typeof GRID_OPTION_KEYS)[number]>>;

function syncGridOptions<TData>(
  engine: GridEngine<TData>,
  options: GridOptions<TData>,
  synced: SyncedGridOptions<TData>,
): void {
  for (const key of GRID_OPTION_KEYS) {
    const value = options[key];
    if (value !== undefined && value !== synced[key]) {
      engine.setOption(key, value as GridOptions<TData>[typeof key]);
      (synced as Record<typeof key, unknown>)[key] = value;
    }
  }
}

function createEngine<TData>(options: GridOptions<TData>): GridEngine<TData> {
  ensureSortModuleRegistered();
  ensureFilterModuleRegistered();
  ensurePaginationModuleRegistered();
  return createGridEngine({
    ...options,
    frameworkCellRenderers: true,
    modules: [...(options.modules ?? []), SortModule, FilterModule, PaginationModule],
  });
}

export function useOlGrid<TData>(options: GridOptions<TData>): UseOlGridResult<TData> {
  const engineRef = useRef<GridEngine<TData> | null>(null);
  const aliveRef = useRef(false);
  const syncedOptionsRef = useRef<SyncedGridOptions<TData>>({});

  if (!engineRef.current) {
    engineRef.current = createEngine(options);
  }

  const engine = engineRef.current;

  useSyncExternalStore(
    (onStoreChange) => engine.getStore().subscribe(onStoreChange),
    () => engine.getStore().getState(),
    () => engine.getStore().getState(),
  );

  useEffect(() => {
    syncGridOptions(engine, options, syncedOptionsRef.current);
    syncEventHandlers(engine, options);
  });

  useEffect(() => {
    aliveRef.current = true;
    return () => {
      aliveRef.current = false;
      queueMicrotask(() => {
        if (!aliveRef.current) {
          engine.destroy();
          engineRef.current = null;
          syncedOptionsRef.current = {};
        }
      });
    };
  }, [engine]);

  return {
    grid: engine,
    api: engine.getApi(),
  };
}

function syncEventHandlers<TData>(engine: GridEngine<TData>, options: GridOptions<TData>): void {
  const opts = engine.getOptions() as GridOptions<TData>;
  opts.onSelectionChanged = options.onSelectionChanged;
  opts.onSortChanged = options.onSortChanged;
  opts.onRowDataUpdated = options.onRowDataUpdated;
  opts.onFilterChanged = options.onFilterChanged;
  opts.onFilterOpened = options.onFilterOpened;
  opts.onDisplayedColumnsChanged = options.onDisplayedColumnsChanged;
  opts.onColumnResized = options.onColumnResized;
  opts.onCellValueChanged = options.onCellValueChanged;
  opts.onSortModelChange = options.onSortModelChange;
  opts.onFilterModelChange = options.onFilterModelChange;
  opts.onSelectionChange = options.onSelectionChange;
  opts.onGridReady = options.onGridReady;
}

export const OlGrid = forwardRef(function OlGrid<TData>(
  { className, style, ...options }: OlGridProps<TData>,
  ref: React.ForwardedRef<OlGridHandle<TData>>,
) {
  const hostRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<ReturnType<typeof createDomRenderer> | null>(null);
  const engineRef = useRef<GridEngine<TData> | null>(null);
  const aliveRef = useRef(false);
  const syncedOptionsRef = useRef<SyncedGridOptions<TData>>({});

  if (!engineRef.current) {
    engineRef.current = createEngine(options);
  }

  const engine = engineRef.current;
  const cellPortals = useCellRendererPortals(engine, rendererRef.current);

  useImperativeHandle(ref, () => ({
    api: engine.getApi(),
    grid: engine,
  }));

  useSyncExternalStore(
    (onStoreChange) => engine.getStore().subscribe(onStoreChange),
    () => engine.getStore().getState(),
    () => engine.getStore().getState(),
  );

  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;

    aliveRef.current = true;
    const renderer = createDomRenderer();
    rendererRef.current = renderer;
    engine.mount(host, renderer);

    return () => {
      aliveRef.current = false;
      engine.unmount();
      rendererRef.current = null;
    };
  }, [engine]);

  useEffect(() => {
    syncGridOptions(engine, options, syncedOptionsRef.current);
    syncEventHandlers(engine, options);
  });

  useEffect(() => {
    return () => {
      queueMicrotask(() => {
        if (!aliveRef.current) {
          engine.destroy();
          engineRef.current = null;
          syncedOptionsRef.current = {};
        }
      });
    };
  }, [engine]);

  return (
    <>
      <div
        ref={hostRef}
        className={className ? `ol-grid-host ${className}` : "ol-grid-host"}
        style={style}
      />
      {cellPortals.map((entry) => entry.portal)}
    </>
  );
}) as <TData>(
  props: OlGridProps<TData> & { ref?: React.ForwardedRef<OlGridHandle<TData>> },
) => React.ReactElement;

// packages/svelte/src/OlGrid.svelte
<script lang="ts">
  import type { GridApi, GridEngine, GridOptions } from "@ol-grid/core";
  import { createDomRenderer } from "@ol-grid/dom-renderer";
  import { createEventDispatcher, onDestroy, onMount } from "svelte";
  import {
    buildGridOptionsFromProps,
    createAdapterEngine,
    GRID_OPTION_KEYS,
    syncEventHandlers,
    syncGridOptions,
  } from "./engine-setup.js";

  export let api: GridApi | null = null;

  export let columnDefs: GridOptions["columnDefs"] = undefined;
  export let defaultColDef: GridOptions["defaultColDef"] = undefined;
  export let sortModel: GridOptions["sortModel"] = undefined;
  export let rowData: GridOptions["rowData"] = undefined;
  export let rowHeight: GridOptions["rowHeight"] = undefined;
  export let rowSelection: GridOptions["rowSelection"] = undefined;
  export let getRowId: GridOptions["getRowId"] = undefined;
  export let context: GridOptions["context"] = undefined;
  export let quickFilterText: GridOptions["quickFilterText"] = undefined;
  export let filterModel: GridOptions["filterModel"] = undefined;
  export let pagination: GridOptions["pagination"] = undefined;
  export let paginationPageSize: GridOptions["paginationPageSize"] = undefined;
  export let paginationPage: GridOptions["paginationPage"] = undefined;
  export let paginationPageSizeSelector: GridOptions["paginationPageSizeSelector"] = undefined;
  export let selectedRowIds: GridOptions["selectedRowIds"] = undefined;
  export let theme: GridOptions["theme"] = undefined;
  export let locale: GridOptions["locale"] = undefined;
  export let localeText: GridOptions["localeText"] = undefined;
  export let localeBundle: GridOptions["localeBundle"] = undefined;
  export let modules: GridOptions["modules"] = undefined;

  export let onGridReady: GridOptions["onGridReady"] = undefined;
  export let onSelectionChanged: GridOptions["onSelectionChanged"] = undefined;
  export let onSortChanged: GridOptions["onSortChanged"] = undefined;
  export let onFilterChanged: GridOptions["onFilterChanged"] = undefined;
  export let onFilterOpened: GridOptions["onFilterOpened"] = undefined;
  export let onDisplayedColumnsChanged: GridOptions["onDisplayedColumnsChanged"] = undefined;
  export let onColumnResized: GridOptions["onColumnResized"] = undefined;
  export let onCellValueChanged: GridOptions["onCellValueChanged"] = undefined;
  export let onRowDataUpdated: GridOptions["onRowDataUpdated"] = undefined;
  export let onSortModelChange: GridOptions["onSortModelChange"] = undefined;
  export let onFilterModelChange: GridOptions["onFilterModelChange"] = undefined;
  export let onSelectionChange: GridOptions["onSelectionChange"] = undefined;

  export let className = "";
  export let style: string | undefined = undefined;

  const dispatch = createEventDispatcher<{ gridReady: { api: GridApi } }>();

  let hostEl: HTMLDivElement;
  let engine: GridEngine | null = null;
  let unsubscribe: (() => void) | null = null;
  let storeVersion = 0;
  const syncedOptions: Partial<Record<(typeof GRID_OPTION_KEYS)[number], unknown>> = {};

  function currentOptions(): GridOptions {
    return buildGridOptionsFromProps({
      columnDefs,
      defaultColDef,
      sortModel,
      rowData,
      rowHeight,
      rowSelection,
      getRowId,
      context,
      quickFilterText,
      filterModel,
      pagination,
      paginationPageSize,
      paginationPage,
      paginationPageSizeSelector,
      selectedRowIds,
      theme,
      locale,
      localeText,
      localeBundle,
      modules,
      onGridReady,
      onSelectionChanged,
      onSortChanged,
      onFilterChanged,
      onFilterOpened,
      onDisplayedColumnsChanged,
      onColumnResized,
      onCellValueChanged,
      onRowDataUpdated,
      onSortModelChange,
      onFilterModelChange,
      onSelectionChange,
    });
  }

  onMount(() => {
    const options = currentOptions();
    engine = createAdapterEngine(options);
    api = engine.getApi();

    const renderer = createDomRenderer();
    engine.mount(hostEl, renderer);
    syncGridOptions(engine, options, syncedOptions);
    syncEventHandlers(engine, options);

    const readyEvent = {
      api: engine.getApi(),
      columnApi: null,
      context: options.context ?? null,
    };
    onGridReady?.(readyEvent);
    dispatch("gridReady", { api: engine.getApi() });

    unsubscribe = engine.getStore().subscribe(() => {
      storeVersion++;
    });
  });

  $: optionsToSync = currentOptions();
  $: if (engine) {
    syncGridOptions(engine, optionsToSync, syncedOptions);
    syncEventHandlers(engine, optionsToSync);
  }

  onDestroy(() => {
    unsubscribe?.();
    engine?.destroy();
    engine = null;
    api = null;
  });
</script>

<div
  bind:this={hostEl}
  class={`ol-grid-host${className ? ` ${className}` : ""}`}
  {style}
  aria-hidden="true"
  data-store-version={storeVersion}
></div>
